Import('env')

build  = env['PATHS']['build']['analysis']
source = env['PATHS']['source']['analysis']

env.BuildStata(target = ['#%s/plot.eps'    % build,
                         '#%s/table.txt'   % build],
               source = ['#%s/analysis.do' % source,
                         '#%s/testing/data_2.txt'    % env['PATHS']['build']['data']])
